<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
    $err_output = function_exists('esc_html') ? esc_html($err) : htmlspecialchars($err, ENT_QUOTES, 'UTF-8'); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err_output); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite -- Third-party Composer/Jetpack library code; WP_Filesystem not applicable here.
        } elseif (!headers_sent()) {
            echo $err_output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Already escaped via esc_html() or htmlspecialchars() above.
        }
    }
    throw new RuntimeException($err); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Exception message used internally, not browser output.
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit0eb06f1c74255d78e06a380a8b0829b5::getLoader();
