<?php
/**
 * SproutOS MCP - Execute PHP Code
 *
 * Runs arbitrary PHP in the full WordPress environment with configurable
 * timeout, optional DB-query capture, and rich execution telemetry.
 *
 * @package SproutOS_MCP
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit();
}

// Register ability definition.

wp_register_ability('sprout/execute-php', [
    'label'       => __('Execute PHP Code', 'sprout-os'),
    'description' => 'Runs PHP code inside the live WordPress environment. All core APIs ($wpdb, WP_Query, get_option ...), loaded plugins, and active theme functions are available. Returns the value from "return ...;", any echoed output, captured warnings/notices, and execution telemetry (timing, memory, query count).',
    'category' => 'sprout-code-execution',

    'input_schema' => [
        'type'       => 'object',
        'properties' => [
            'code' => [
                'type'        => 'string',
                'minLength'   => 1,
                'description' => 'PHP code to run. Omit the opening <?php tag. '
                    . 'Use "return $val;" to pass data back to the caller.',
            ],
            'timeout' => [
                'type'        => 'integer',
                'minimum'     => 1,
                'maximum'     => 120,
                'default'     => SPROUT_MCP_MAX_EXECUTION_TIME,
                'description' => 'Maximum seconds the code may run (1–120). '
                    . 'Defaults to ' . SPROUT_MCP_MAX_EXECUTION_TIME . 's.',
            ],
            'capture_queries' => [
                'type'        => 'boolean',
                'default'     => false,
                'description' => 'When true, every database query fired during '
                    . 'execution is recorded and returned in the response. '
                    . 'Useful for profiling and debugging.',
            ],
        ],
        'required'             => ['code'],
        'additionalProperties' => false,
    ],

    'output_schema' => [
        'type'       => 'object',
        'properties' => [
            'success'      => [
                'type'        => 'boolean',
                'description' => 'True when the code completed without throwing.',
            ],
            'return_value' => [
                'description' => 'The value produced by "return …;" in the code.',
            ],
            'output' => [
                'type'        => 'string',
                'description' => 'Text emitted via echo, print, or var_dump.',
            ],
            'errors' => [
                'type'        => 'array',
                'description' => 'PHP warnings, notices, and deprecations.',
                'items'       => [
                    'type'       => 'object',
                    'properties' => [
                        'type'    => ['type' => 'string'],
                        'message' => ['type' => 'string'],
                        'file'    => ['type' => 'string'],
                        'line'    => ['type' => 'integer'],
                    ],
                ],
            ],
            'error_message' => [
                'type'        => 'string',
                'description' => 'Exception / Error message when execution fails.',
            ],
            'error_class' => [
                'type'        => 'string',
                'description' => 'Fully-qualified class name of the thrown Throwable.',
            ],
            'execution_time_ms' => [
                'type'        => 'number',
                'description' => 'Wall-clock milliseconds the code took.',
            ],
            'memory_used_bytes' => [
                'type'        => 'integer',
                'description' => 'Memory consumed during execution (bytes).',
            ],
            'peak_memory_bytes' => [
                'type'        => 'integer',
                'description' => 'Peak memory reached during execution (bytes).',
            ],
            'queries_count' => [
                'type'        => 'integer',
                'description' => 'Number of DB queries fired during execution.',
            ],
            'queries' => [
                'type'        => 'array',
                'description' => 'Individual queries (only when capture_queries is true).',
                'items'       => [
                    'type'       => 'object',
                    'properties' => [
                        'sql'     => ['type' => 'string'],
                        'time_ms' => ['type' => 'number'],
                    ],
                ],
            ],
            'run_id' => [
                'type'        => 'string',
                'description' => 'Unique execution identifier generated by Sprout for traceability.',
            ],
            'query_capture_mode' => [
                'type'        => 'string',
                'description' => 'Either "detailed" or "summary".',
            ],
            'runtime_profile' => [
                'type'       => 'object',
                'properties' => [
                    'timeout_seconds' => ['type' => 'integer'],
                    'memory_delta_bytes' => ['type' => 'integer'],
                    'policy_tag' => ['type' => 'string'],
                ],
                'required' => ['timeout_seconds', 'memory_delta_bytes', 'policy_tag'],
            ],
        ],
    ],

    'execute_callback'    => 'sprout_mcp_execute_php',
    'permission_callback' => 'sprout_mcp_permission_callback',

    'meta' => [
        'show_in_rest' => true,
        'mcp'          => ['public' => true],
        'annotations'  => [
            'title'       => 'Execute PHP Code',
            'instructions' => implode("\n", [
                'SAFETY GUIDELINES:',
                '• Never call exit() or die() - it terminates the whole PHP process.',
                '• Avoid infinite loops - the configurable timeout (default '
                    . SPROUT_MCP_MAX_EXECUTION_TIME . 's) will terminate execution.',
                '• Omit <?php opening tags - the code is evaluated directly.',
                '• Use "return $value;" to send data back (captured as return_value).',
                '• echo / print output appears in the "output" field.',
                '',
                'AVAILABLE CONTEXT:',
                '• WordPress core: $wpdb, get_option(), WP_Query, WP_REST_Request …',
                '• Every active plugin and theme function.',
                '• Globals: $wp_version, $wp_rewrite, $wp_registered_sidebars …',
                '',
                'PROFILING:',
                '• Set capture_queries to true to receive every SQL query in the response.',
                '• The response always includes execution_time_ms, memory_used_bytes,',
                '  peak_memory_bytes, and queries_count for performance awareness.',
                '',
                'PERSISTENT CODE:',
                '• To create code that survives across requests, write a file to the',
                '  sandbox (wp-content/sproutos-mcp-sandbox/) via sprout/write-file.',
                '• Code run here via eval is temporary - it does not persist.',
            ]),
            'readonly'    => false,
            'destructive' => true,
            'idempotent'  => false,
        ],
    ],
]);

// Execute runtime logic and collect telemetry.

/**
 * Run user-supplied PHP code with full telemetry.
 *
 * @param array{code: string, timeout?: int, capture_queries?: bool} $input
 * @return array<string, mixed>
 */
function sprout_mcp_execute_php(array $input): array
{
    $php_source      = (string) $input['code'];
    $timeout_seconds = sprout_mcp_clamp_timeout($input);
    $capture_detail  = !empty($input['capture_queries']);
    $execution_id    = function_exists('wp_generate_uuid4') ? wp_generate_uuid4() : uniqid('sprout_exec_', true);

    // Snapshot pre-execution state.
    $memory_before = memory_get_usage();
    $peak_before   = memory_get_peak_usage();
    $queries_before = sprout_mcp_query_count();

    // Start DB-query recording when requested.
    if ($capture_detail) {
        sprout_mcp_start_query_capture();
    }

    // Run the code inside an isolated helper that manages the
    // error handler, output buffer, and time limit.
    $execution_result = sprout_mcp_run_eval($php_source, $timeout_seconds);

    // Collect telemetry.
    $memory_after = memory_get_usage();
    $peak_after   = memory_get_peak_usage();

    $execution_result['memory_used_bytes'] = max(0, $memory_after - $memory_before);
    $execution_result['peak_memory_bytes'] = max($peak_before, $peak_after);
    $execution_result['queries_count']     = sprout_mcp_query_count() - $queries_before;
    $execution_result['run_id']            = $execution_id;
    $execution_result['query_capture_mode']= $capture_detail ? 'detailed' : 'summary';
    $execution_result['runtime_profile']   = [
        'timeout_seconds'    => $timeout_seconds,
        'memory_delta_bytes' => max(0, $memory_after - $memory_before),
        'policy_tag'         => 'sprout-exec-v2',
    ];

    if ($capture_detail) {
        $execution_result['queries'] = sprout_mcp_stop_query_capture();
    }

    return $execution_result;
}

// Internal helper functions.

/**
 * Clamp and return the timeout from user input.
 *
 * @param array $input Raw input array.
 * @return int  Seconds between 1 and 120.
 */
function sprout_mcp_clamp_timeout(array $input): int
{
    $default = SPROUT_MCP_MAX_EXECUTION_TIME;
    $val     = isset($input['timeout']) ? (int) $input['timeout'] : $default;

    return max(1, min(120, $val));
}

/**
 * Evaluate PHP code inside an output buffer with an error handler.
 *
 * @param string $code    PHP source without <?php tag.
 * @param int    $timeout Maximum seconds.
 * @return array{success: bool, return_value: mixed, output: string, errors: list<array>, execution_time_ms: float, error_message?: string, error_class?: string}
 */
function sprout_mcp_run_eval(string $code, int $timeout): array
{
    $captured_errors = [];

    // Sprout MCP: human-readable PHP error severity labels.
    $sprout_error_labels = [
        E_WARNING        => 'PHP Warning',
        E_NOTICE         => 'PHP Notice',
        E_DEPRECATED     => 'PHP Deprecated',
        E_USER_WARNING   => 'User Warning',
        E_USER_NOTICE    => 'User Notice',
        E_USER_DEPRECATED => 'User Deprecated',
        E_STRICT         => 'Strict Standards',
    ];

    $prev_limit = (int) ini_get('max_execution_time');
    // phpcs:ignore Squiz.PHP.DiscouragedFunctions.Discouraged
    set_time_limit($timeout);

    // Capture warnings / notices without halting execution.
    // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_set_error_handler
    set_error_handler(static function (int $errno, string $msg, string $file, int $line) use (&$captured_errors, $sprout_error_labels): bool {
        $captured_errors[] = [
            'type'    => $sprout_error_labels[$errno] ?? "Unknown ($errno)",
            'message' => $msg,
            'file'    => $file,
            'line'    => $line,
        ];
        return true;
    });

    ob_start();
    $clock_start = hrtime(true);

    $return_value  = null;
    $success       = true;
    $error_message = null;
    $error_class   = null;

    try {
        /** @var mixed $return_value */
        $return_value = eval($code); // @codingStandardsIgnoreLine
    } catch (\Throwable $thrown) {
        $success       = false;
        $error_message = $thrown->getMessage();
        $error_class   = get_class($thrown);
    }

    $elapsed_ms = round((hrtime(true) - $clock_start) / 1e6, 2);
    $output     = (string) ob_get_clean();

    restore_error_handler();
    // phpcs:ignore Squiz.PHP.DiscouragedFunctions.Discouraged
    set_time_limit($prev_limit);

    // Guarantee the return value can be JSON-encoded.
    if ($return_value !== null && json_encode($return_value) === false) {
        // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_print_r
        $return_value = print_r($return_value, true);
    }

    $result = [
        'success'           => $success,
        'return_value'      => $return_value,
        'output'            => $output,
        'errors'            => $captured_errors,
        'execution_time_ms' => $elapsed_ms,
    ];

    if ($error_message !== null) {
        $result['error_message'] = $error_message;
        $result['error_class']   = $error_class;
    }

    return $result;
}

/**
 * Return the current count of DB queries WordPress has executed.
 *
 * @return int
 */
function sprout_mcp_query_count(): int
{
    global $wpdb;
    return (int) $wpdb->num_queries;
}

/**
 * Begin recording individual SQL queries via SAVEQUERIES.
 *
 * @return void
 */
function sprout_mcp_start_query_capture(): void
{
    if (!defined('SAVEQUERIES')) {
        // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
        define('SAVEQUERIES', true);
    }
    // Mark starting index.
    global $wpdb;
    $wpdb->sprout_query_start = count($wpdb->queries ?? []);
}

/**
 * Stop recording and return the queries fired since capture started.
 *
 * Each entry contains the SQL string and execution time in milliseconds.
 * Truncates SQL to 500 characters to keep the response manageable.
 *
 * @return list<array{sql: string, time_ms: float}>
 */
function sprout_mcp_stop_query_capture(): array
{
    global $wpdb;
    $start   = (int) ($wpdb->sprout_query_start ?? 0);
    $queries = array_slice($wpdb->queries ?? [], $start);

    $result = [];
    foreach ($queries as $q) {
        $result[] = [
            'sql'     => mb_strimwidth((string) ($q[0] ?? ''), 0, 500, '…'),
            'time_ms' => round((float) ($q[1] ?? 0) * 1000, 2),
        ];
    }

    return $result;
}
