<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
$baseDir = dirname($vendorDir); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.

return array(
    'WP\\MCP\\' => array($vendorDir . '/wordpress/mcp-adapter/includes'),
    'Automattic\\Jetpack\\Autoloader\\' => array($vendorDir . '/automattic/jetpack-autoloader/src'),
);
