<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
$baseDir = dirname($vendorDir); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.

return array(
);
