<?php return array(
    'root' => array(
        'name' => 'posimyth/sproutos-mcp',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '194a52504de5b0cdeda4eb22fcc7c9439e591f6c',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'automattic/jetpack-autoloader' => array(
            'pretty_version' => 'v5.0.16',
            'version' => '5.0.16.0',
            'reference' => 'd8ae822a35e7431137e860ee60eceedaa745e4d1',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../automattic/jetpack-autoloader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'posimyth/sproutos-mcp' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '194a52504de5b0cdeda4eb22fcc7c9439e591f6c',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wordpress/mcp-adapter' => array(
            'pretty_version' => 'v0.4.1',
            'version' => '0.4.1.0',
            'reference' => '1a0f9ab868e34b4375be42e873f60765e6632505',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wordpress/mcp-adapter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
