<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// This file `jetpack_autoload_classmap.php` was auto generated by automattic/jetpack-autoloader.

$vendorDir = dirname(__DIR__); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
$baseDir   = dirname($vendorDir); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.

return array(
	'Autoloader' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader.php'
	),
	'Autoloader_Handler' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader-handler.php'
	),
	'Autoloader_Locator' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader-locator.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadFileWriter' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadFileWriter.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadGenerator' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadGenerator.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadProcessor' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadProcessor.php'
	),
	'Automattic\\Jetpack\\Autoloader\\CustomAutoloaderPlugin' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/CustomAutoloaderPlugin.php'
	),
	'Automattic\\Jetpack\\Autoloader\\ManifestGenerator' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/ManifestGenerator.php'
	),
	'Container' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-container.php'
	),
	'Hook_Manager' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-hook-manager.php'
	),
	'Latest_Autoloader_Guard' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-latest-autoloader-guard.php'
	),
	'Manifest_Reader' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-manifest-reader.php'
	),
	'PHP_Autoloader' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-php-autoloader.php'
	),
	'Path_Processor' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-path-processor.php'
	),
	'Plugin_Locator' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-plugin-locator.php'
	),
	'Plugins_Handler' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-plugins-handler.php'
	),
	'Shutdown_Handler' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-shutdown-handler.php'
	),
	'Version_Loader' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-version-loader.php'
	),
	'Version_Selector' => array(
		'version' => '5.0.16',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-version-selector.php'
	),
	'WP\\MCP\\Abilities\\DiscoverAbilitiesAbility' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Abilities/DiscoverAbilitiesAbility.php'
	),
	'WP\\MCP\\Abilities\\ExecuteAbilityAbility' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Abilities/ExecuteAbilityAbility.php'
	),
	'WP\\MCP\\Abilities\\GetAbilityInfoAbility' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Abilities/GetAbilityInfoAbility.php'
	),
	'WP\\MCP\\Abilities\\McpAbilityHelperTrait' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Abilities/McpAbilityHelperTrait.php'
	),
	'WP\\MCP\\Autoloader' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Autoloader.php'
	),
	'WP\\MCP\\Cli\\McpCommand' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Cli/McpCommand.php'
	),
	'WP\\MCP\\Cli\\StdioServerBridge' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Cli/StdioServerBridge.php'
	),
	'WP\\MCP\\Core\\McpAdapter' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Core/McpAdapter.php'
	),
	'WP\\MCP\\Core\\McpComponentRegistry' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Core/McpComponentRegistry.php'
	),
	'WP\\MCP\\Core\\McpServer' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Core/McpServer.php'
	),
	'WP\\MCP\\Core\\McpTransportFactory' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Core/McpTransportFactory.php'
	),
	'WP\\MCP\\Domain\\Prompts\\Contracts\\McpPromptBuilderInterface' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Prompts/Contracts/McpPromptBuilderInterface.php'
	),
	'WP\\MCP\\Domain\\Prompts\\McpPrompt' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Prompts/McpPrompt.php'
	),
	'WP\\MCP\\Domain\\Prompts\\McpPromptBuilder' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Prompts/McpPromptBuilder.php'
	),
	'WP\\MCP\\Domain\\Prompts\\McpPromptValidator' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Prompts/McpPromptValidator.php'
	),
	'WP\\MCP\\Domain\\Prompts\\RegisterAbilityAsMcpPrompt' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Prompts/RegisterAbilityAsMcpPrompt.php'
	),
	'WP\\MCP\\Domain\\Resources\\McpResource' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Resources/McpResource.php'
	),
	'WP\\MCP\\Domain\\Resources\\McpResourceValidator' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Resources/McpResourceValidator.php'
	),
	'WP\\MCP\\Domain\\Resources\\RegisterAbilityAsMcpResource' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Resources/RegisterAbilityAsMcpResource.php'
	),
	'WP\\MCP\\Domain\\Tools\\McpTool' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Tools/McpTool.php'
	),
	'WP\\MCP\\Domain\\Tools\\McpToolValidator' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Tools/McpToolValidator.php'
	),
	'WP\\MCP\\Domain\\Tools\\RegisterAbilityAsMcpTool' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Tools/RegisterAbilityAsMcpTool.php'
	),
	'WP\\MCP\\Domain\\Utils\\McpAnnotationMapper' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Utils/McpAnnotationMapper.php'
	),
	'WP\\MCP\\Domain\\Utils\\McpValidator' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Utils/McpValidator.php'
	),
	'WP\\MCP\\Domain\\Utils\\SchemaTransformer' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Domain/Utils/SchemaTransformer.php'
	),
	'WP\\MCP\\Handlers\\HandlerHelperTrait' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/HandlerHelperTrait.php'
	),
	'WP\\MCP\\Handlers\\Initialize\\InitializeHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/Initialize/InitializeHandler.php'
	),
	'WP\\MCP\\Handlers\\Prompts\\PromptsHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/Prompts/PromptsHandler.php'
	),
	'WP\\MCP\\Handlers\\Resources\\ResourcesHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/Resources/ResourcesHandler.php'
	),
	'WP\\MCP\\Handlers\\System\\SystemHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/System/SystemHandler.php'
	),
	'WP\\MCP\\Handlers\\Tools\\ToolsHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Handlers/Tools/ToolsHandler.php'
	),
	'WP\\MCP\\Infrastructure\\ErrorHandling\\Contracts\\McpErrorHandlerInterface' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/ErrorHandling/Contracts/McpErrorHandlerInterface.php'
	),
	'WP\\MCP\\Infrastructure\\ErrorHandling\\ErrorLogMcpErrorHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/ErrorHandling/ErrorLogMcpErrorHandler.php'
	),
	'WP\\MCP\\Infrastructure\\ErrorHandling\\McpErrorFactory' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/ErrorHandling/McpErrorFactory.php'
	),
	'WP\\MCP\\Infrastructure\\ErrorHandling\\NullMcpErrorHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/ErrorHandling/NullMcpErrorHandler.php'
	),
	'WP\\MCP\\Infrastructure\\Observability\\ConsoleObservabilityHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/Observability/ConsoleObservabilityHandler.php'
	),
	'WP\\MCP\\Infrastructure\\Observability\\Contracts\\McpObservabilityHandlerInterface' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/Observability/Contracts/McpObservabilityHandlerInterface.php'
	),
	'WP\\MCP\\Infrastructure\\Observability\\ErrorLogMcpObservabilityHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/Observability/ErrorLogMcpObservabilityHandler.php'
	),
	'WP\\MCP\\Infrastructure\\Observability\\McpObservabilityHelperTrait' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/Observability/McpObservabilityHelperTrait.php'
	),
	'WP\\MCP\\Infrastructure\\Observability\\NullMcpObservabilityHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Infrastructure/Observability/NullMcpObservabilityHandler.php'
	),
	'WP\\MCP\\Plugin' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Plugin.php'
	),
	'WP\\MCP\\Servers\\DefaultServerFactory' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Servers/DefaultServerFactory.php'
	),
	'WP\\MCP\\Transport\\Contracts\\McpRestTransportInterface' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Contracts/McpRestTransportInterface.php'
	),
	'WP\\MCP\\Transport\\Contracts\\McpTransportInterface' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Contracts/McpTransportInterface.php'
	),
	'WP\\MCP\\Transport\\HttpTransport' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/HttpTransport.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\HttpRequestContext' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/HttpRequestContext.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\HttpRequestHandler' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/HttpRequestHandler.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\HttpSessionValidator' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/HttpSessionValidator.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\JsonRpcResponseBuilder' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/JsonRpcResponseBuilder.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\McpTransportContext' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/McpTransportContext.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\McpTransportHelperTrait' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/McpTransportHelperTrait.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\RequestRouter' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/RequestRouter.php'
	),
	'WP\\MCP\\Transport\\Infrastructure\\SessionManager' => array(
		'version' => '0.4.1.0',
		'path'    => $vendorDir . '/wordpress/mcp-adapter/includes/Transport/Infrastructure/SessionManager.php'
	),
);
