<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// platform_check.php @generated by Composer

$issues = array(); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.

if (!(PHP_VERSION_ID >= 70400)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.4.0". You are running ' . PHP_VERSION . '.'; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Third-party auto-generated Composer/Jetpack code.
}

if ($issues) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite -- Third-party Composer code; WP_Filesystem is not applicable in this CLI context.
        } elseif (!headers_sent()) {
            // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CLI/plain-text context only, not rendered as HTML.
            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }
    }
    // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_trigger_error, WordPress.Security.EscapeOutput.OutputNotEscaped
    trigger_error(
        'Composer detected issues in your platform: ' . implode(' ', $issues), // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain-text passed to trigger_error, not browser output.
        E_USER_ERROR
    );
}
